openapi: 3.0.1
info:
  title: Personal Finances - API
  description: API to control your personal finances.
  version: 0.0.1
servers:
- url: http://localhost/PersonalFin/api/public
  description: API de Teste
paths:
  /login:
    post:
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /client:
    post:
      summary: Create new client
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientQuery"
  /clients:
    get:
      summary: Get all clients
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ClientQuery"
  /client/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get client by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/ClientQuery"
    put:
      summary: Edit client
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientQuery"
    delete:
      summary: Delete client
      responses:
        201:
          description: "Success"
          content:
            text:
              example: 1
              
  /suggestedPayments:
    get:
      summary: Get all suggested payment
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SuggestedPayment"
  /suggestedPayment/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get suggested payment by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/SuggestedPayment"
                    
  /suggestedCategories:
    get:
      summary: Get all suggested category
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SuggestedCategory"
  /suggestedCategory/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get suggested category by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/SuggestedCategory"
  
  /payment:
    post:
      summary: Create new payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentQuery"
  /payments:
    get:
      summary: Get all payments
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/PaymentQuery"
  /payment/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get payment by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/PaymentQuery"
    put:
      summary: Edit payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentQuery"
    delete:
      summary: Delete payment
      responses:
        201:
          description: "Success"
          content:
            text:
              example: 1
  /category:
    post:
      summary: Create new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryQuery"
  /categories:
    get:
      summary: Get all categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/CategoryQuery"
  /category/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get category by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/CategoryQuery"
    put:
      summary: Edit category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryQuery"
    delete:
      summary: Delete category
      responses:
        201:
          description: "Success"
          content:
            text:
              example: 1

  /bank:
    post:
      summary: Create new bank
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankQuery"
  /banks:
    get:
      summary: Get all banks
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/BankQuery"
  /bank/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get bank by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/BankQuery"
    put:
      summary: Edit bank
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankQuery"
    delete:
      summary: Delete bank
      responses:
        201:
          description: "Success"
          content:
            text:
              example: 1

  /bankAccount:
    post:
      summary: Create new bank account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankAccountEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountQuery"
  /bankAccounts:
    get:
      summary: Get all bank accounts
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  page:
                    type: integer
                  itemsPerPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/BankAccountQuery"
  /bankAccount/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Get bank account by id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    $ref: "#/components/schemas/BankAccountQuery"
    put:
      summary: Edit bankAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankAccountEdit"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountQuery"
    delete:
      summary: Delete bankAccount
      responses:
        201:
          description: "Success"
          content:
            text:
              example: 1
security: 
- auth: []
components:
  schemas:
    User:
      type: object
      properties:
        user:
          type: string
        password:
          type: string
          
    ClientQuery:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        name: 
          type: string
        email:
          type: string
    ClientEdit:
      type: object
      properties:
        name: 
          type: string
        email:
          type: string
    
    SuggestedPayment:
      type: object
      properties:
        name: 
          type: string
        initials: 
          type: string
    SuggestedCategory:
      type: object
      properties:
        shortName: 
          type: string
        name: 
          type: string
          
    PaymentQuery:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
        initials:
          type: string
    PaymentEdit:
      type: object
      properties:
        name: 
          type: string
        initials:
          type: string
    
    CategoryQuery:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
        shortName:
          type: string
    CategoryEdit:
      type: object
      properties:
        name: 
          type: string
        shortName:
          type: string

    BankQuery:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
    BankEdit:
      type: object
      properties:
        name: 
          type: string

    BankAccountQuery:
      type: object
      properties:
        id:
          type: integer
        bankId:
          type: integer
        name: 
          type: string
        investiment:
          type: boolean
        displayInSummary:
          type: boolean
    BankAccountEdit:
      type: object
      properties:
        bankId:
          type: integer
        name: 
          type: string
        investiment:
          type: boolean
        displayInSummary:
          type: boolean
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT