#index:
#    path: /
#    controller: App\Controller\DefaultController::index
###### CLIENT ###########
clients:
  path: /clients
  methods:
    - GET
  controller: App\Controller\ClientController::getAll
client:
  path: /client/{id}
  methods:
    - GET
  controller: App\Controller\ClientController::getOne
new_client:
  path: /client
  methods:
    - POST
  controller: App\Controller\ClientController::new
update_client:
  path: /client/{id}
  methods:
    - PUT
  controller: App\Controller\ClientController::update
delete_client:
  path: /client/{id}
  methods:
    - DELETE
  controller: App\Controller\ClientController::delete

  ###### Suggested Payment ###########
suggestedPayments:
  path: /suggestedPayments
  methods:
    - GET
  controller: App\Controller\SuggestedPaymentController::getAll
suggestedPayment:
  path: /suggestedPayment/{id}
  methods:
    - GET
  controller: App\Controller\SuggestedPaymentController::getOne

    ###### Suggested Category ###########
suggestedCategories:
  path: /suggestedCategories
  methods:
    - GET
  controller: App\Controller\SuggestedCategoryController::getAll
suggestedCategory:
  path: /suggestedCategory/{id}
  methods:
    - GET
  controller: App\Controller\SuggestedCategoryController::getOne

###### Payment ###########
payments:
  path: /payments
  methods:
    - GET
  controller: App\Controller\PaymentController::getAll
payment:
  path: /payment/{id}
  methods:
    - GET
  controller: App\Controller\PaymentController::getOne
new_payment:
  path: /payment
  methods:
    - POST
  controller: App\Controller\PaymentController::new
update_payment:
  path: /payment/{id}
  methods:
    - PUT
  controller: App\Controller\PaymentController::update
delete_payment:
  path: /payment/{id}
  methods:
    - DELETE
  controller: App\Controller\PaymentController::delete

###### Category ###########
rows_category:
  path: /category/totalRows
  methods:
    - GET
  controller: App\Controller\CategoryController::getTotalRows
categories:
  path: /categories
  methods:
    - GET
  controller: App\Controller\CategoryController::getAll
category:
  path: /category/{id}
  methods:
    - GET
  controller: App\Controller\CategoryController::getOne
new_category:
  path: /category
  methods:
    - POST
  controller: App\Controller\CategoryController::new
update_category:
  path: /category/{id}
  methods:
    - PUT
  controller: App\Controller\CategoryController::update
delete_category:
  path: /category/{id}
  methods:
    - DELETE
  controller: App\Controller\CategoryController::delete

###### Bank ###########
banks:
  path: /banks
  methods:
    - GET
  controller: App\Controller\BankController::getAll
bank:
  path: /bank/{id}
  methods:
    - GET
  controller: App\Controller\BankController::getOne
new_bank:
  path: /bank
  methods:
    - POST
  controller: App\Controller\BankController::new
update_bank:
  path: /bank/{id}
  methods:
    - PUT
  controller: App\Controller\BankController::update
delete_bank:
  path: /bank/{id}
  methods:
    - DELETE
  controller: App\Controller\BankController::delete

###### BankAccount ###########
bankAccounts:
  path: /bankAccounts
  methods:
    - GET
  controller: App\Controller\BankAccountController::getAll
bankAccount:
  path: /bankAccount/{id}
  methods:
    - GET
  controller: App\Controller\BankAccountController::getOne
new_bankAccount:
  path: /bankAccount
  methods:
    - POST
  controller: App\Controller\BankAccountController::new
update_bankAccount:
  path: /bankAccount/{id}
  methods:
    - PUT
  controller: App\Controller\BankAccountController::update
delete_bankAccount:
  path: /bankAccount/{id}
  methods:
    - DELETE
  controller: App\Controller\BankAccountController::delete

###### CreditCard ###########
creditCards:
  path: /creditCards
  methods:
    - GET
  controller: App\Controller\CreditCardController::getAll
creditCard:
  path: /creditCard/{id}
  methods:
    - GET
  controller: App\Controller\CreditCardController::getOne
new_creditCard:
  path: /creditCard
  methods:
    - POST
  controller: App\Controller\CreditCardController::new
update_creditCard:
  path: /creditCard/{id}
  methods:
    - PUT
  controller: App\Controller\CreditCardController::update
delete_creditCard:
  path: /creditCard/{id}
  methods:
    - DELETE
  controller: App\Controller\CreditCardController::delete

  ###### Entry ###########
entries:
  path: /entries
  methods:
    - GET
  controller: App\Controller\EntryController::getAll
entriesDate:
  path: /entries/byDate/{dtBegin}/{dtEnd}
  methods:
    - GET
  controller: App\Controller\EntryController::getByDate
entriesResume:
  path: /entries/resume/{dtBegin}/{dtEnd}
  methods:
    - GET
  controller: App\Controller\EntryController::getResume
entry:
  path: /entry/{id}
  methods:
    - GET
  controller: App\Controller\EntryController::getOne
new_entry:
  path: /entry
  methods:
    - POST
  controller: App\Controller\EntryController::new
update_entry:
  path: /entry/{id}
  methods:
    - PUT
  controller: App\Controller\EntryController::update
delete_entry:
  path: /entry/{id}
  methods:
    - DELETE
  controller: App\Controller\EntryController::delete