#index:
#    path: /
#    controller: App\Controller\DefaultController::index
###### CLIENT ###########
clients:
  path: /clients
  methods:
    - GET
  controller: App\Controller\ClientController::getAll
client:
  path: /client/{id}
  methods:
    - GET
  controller: App\Controller\ClientController::getOne
new_client:
  path: /client
  methods:
    - POST
  controller: App\Controller\ClientController::new
update_client:
  path: /client/{id}
  methods:
    - PUT
  controller: App\Controller\ClientController::update
delete_client:
  path: /client/{id}
  methods:
    - DELETE
  controller: App\Controller\ClientController::delete

  ###### Suggested Payment ###########
suggestedPayments:
  path: /suggestedPayments
  methods:
    - GET
  controller: App\Controller\SuggestedPaymentController::getAll
suggestedPayment:
  path: /suggestedPayment/{id}
  methods:
    - GET
  controller: App\Controller\SuggestedPaymentController::getOne

    ###### Suggested Category ###########
suggestedCategories:
  path: /suggestedCategories
  methods:
    - GET
  controller: App\Controller\SuggestedCategoryController::getAll
suggestedCategory:
  path: /suggestedCategory/{id}
  methods:
    - GET
  controller: App\Controller\SuggestedCategoryController::getOne

###### Payment ###########
payments:
  path: /payments
  methods:
    - GET
  controller: App\Controller\PaymentController::getAll
payment:
  path: /payment/{id}
  methods:
    - GET
  controller: App\Controller\PaymentController::getOne
new_payment:
  path: /payment
  methods:
    - POST
  controller: App\Controller\PaymentController::new
update_payment:
  path: /payment/{id}
  methods:
    - PUT
  controller: App\Controller\PaymentController::update
delete_payment:
  path: /payment/{id}
  methods:
    - DELETE
  controller: App\Controller\PaymentController::delete